### ISSUE TITLE
二级标题中的公式不适用底色

### ISSUE THREAD

**Issue by Anyayay** [YiNNx/typora-theme-lapis#10]
![image](https://user-images.githubusercontent.com/37764175/236629897-671a7871-a7b8-4b1c-9a90-cc1101c9675b.png)
'  ## abc$5$de

**Comment by YiNNx** [comment]
添加如下代码应该能修复底色不统一问题

```css

#write h2 span.md-inline-math {
  background: var(--primary-color);
  padding: 1px 15px 2px;
  border-radius: 4px;
  font-weight: bold;
  color: #ffffff;
  line-height: 1.44;
}

#write h2 span.md-inline-math script {
  color: #ffffff;
}

```

不过由于二级标题样式是通过 `span` 来实现的，当公式和常规文本混杂时依然会存在样式问题

![image](https://github.com/YiNNx/typora-theme-lapis/assets/86649490/0629d9b7-8a3e-4a67-a722-19b6e283b7a8)

其他格式混杂时同样有这个问题，比如 [#4](https://github.com/YiNNx/typora-theme-lapis/issues/4#issuecomment-1533675752)，还没找到比较好的解决办法

**Comment by Anyayay** [comment]
我有一个偏方可以解决（但也不是什么很好的方法）
同时也解决了 #39 的问题

```css
#write h2 span.md-plain {
    background: var(--header-span-color);
    padding: 1px 15px 2px;
    border-radius: 4px;
    font-weight: bold;
    color: #ffffff;
}

#write h2 span.md-link {
    background: var(--header-span-color);
    padding: 1px 11px 2px; /*修改高度，使得能够对齐*/
    border-radius: 4px;
    margin-left: -6px; /*添加margin*/
    margin-right: -6px; /*添加margin*/
}

#write h2 span.md-link .md-plain {
    background: #ffffff00;
    padding: 1px 0px 3px;
}

#write h2 span.md-content {
    color: #ffffff;
}

#write h2.md-heading a {
    border-bottom: 1px solid white;
}

#write h2 span.md-inline-math {
    background: var(--header-span-color);
    padding: 1px 15px 2px;
    border-radius: 4px;
    font-weight: bold;
    color: #ffffff;
    line-height: 1.44;
    margin-left: -6px; /*添加margin*/
    margin-right: -6px; /*添加margin*/
}

#write h2 span.md-inline-math script {
    color: #ffffff;
}
```

![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/6d54beab-43b8-477b-baac-5a3fc15b54c4)
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/302b4e16-8712-47e4-ba5f-5080f502ac44)

但是存在一个问题：当以公式为标题的开头时（虽然这样场景比较少），会向前缩进
