### ISSUE TITLE
部分字符透明

### ISSUE THREAD

**Issue by yujie003** [YiNNx/typora-theme-lapis#28]
我这里出现了很奇怪的bug，部分字符会变成透明的，字符本身仍然正常占一个位置，但是不会显示。在文件树和md文件内出现了这种情况，比如t和p，但不是所有t和p，比较没规律。

**Comment by YiNNx** [comment]
这是由字体文件不适配导致的bug，参见 issue #19 和 #20
在最新的 [Release](https://github.com/YiNNx/typora-theme-lapis/releases/tag/v1.0.0) 里已经更换了新的字体文件，请重新下载更换 Release 版本，看看还没有显示问题

**Comment by yujie003** [comment]
> 这是由字体文件不适配导致的bug，参见 issue #19 和 #20
> 在最新的 [Release](https://github.com/YiNNx/typora-theme-lapis/releases/tag/v1.0.0) 里已经更换了新的字体文件，请重新下载更换 Release 版本，看看还没有显示问题

我尝试了新的release，问题依然存在

**Comment by YiNNx** [comment]
再试试这条评论里的字体文件？https://github.com/YiNNx/typora-theme-lapis/issues/19#issuecomment-1556903282 
同时在lapis.css中修改对应的文件名并重启 typora
或者你也可以直接注释或删除掉下面的代码，不使用 Cantarell 字体，这样应该就能正常显示了
```css
@font-face {
    font-family: "Cantarell";
    src: url('lapis/Cantarell-VF-new.otf');
}
```
