### ISSUE TITLE
在mac上面左侧滚动存在问题

### ISSUE THREAD

**Issue by leizhiyuan** [YiNNx/typora-theme-lapis#3]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/2684384/235600790-1fb5ad07-bf65-405b-836b-6110096b3246.png">

可以看到展开之后，左侧的命令行有丢失，并且无法滚动

正常情况下，这个位置也很奇怪。
<img width="351" alt="image" src="https://user-images.githubusercontent.com/2684384/235600919-827f22ee-1b3d-42d5-9684-3018bf81e00e.png">

**Comment by YiNNx** [comment]
由于我没有mac环境，可能无法复现图中的问题:thinking:

无法滚动应该是因为主题把侧边栏的滚动条隐藏了，可以试试把`lapis.css`中的

```css
#outline-content::-webkit-scrollbar { width: 0; }
#file-library::-webkit-scrollbar { width: 0; }
```

修改为

```css
#outline-content::-webkit-scrollbar { width: 0.4rem; }
#file-library::-webkit-scrollbar { width: 0.4rem; }
```

看看是否能正常滚动

**Comment by leizhiyuan** [comment]
改过测试不行。
<img width="591" alt="image" src="https://user-images.githubusercontent.com/2684384/236093573-7d9334c7-b1f6-4d6d-a417-ff4d24d4bf70.png">

没有环境复线就先忽略好了。。

**Comment by hefengzz** [comment]
> 

并且文件树视图也有偏移的问题
<img width="316" alt="图片" src="https://github.com/YiNNx/typora-theme-lapis/assets/49849782/9b32f6c8-7a09-409b-9a4b-a5c7e6aed535">

**Comment by YiNNx** [comment]
> 并且文件树视图也有偏移的问题 <img alt="图片" width="316" src="https://user-images.githubusercontent.com/49849782/237571957-9b32f6c8-7a09-409b-9a4b-a5c7e6aed535.png">

是的，感觉mac侧边栏样式整个都有问题......之前拿mac复现了一下，这几天有空来修一修

**Comment by qiudxx** [comment]
我碰到了这个问题，特别喜欢这个主题，希望能修复

**Comment by YiNNx** [comment]
已修复！

<img width="530" alt="截屏2023-05-17 21 37 22" src="https://github.com/YiNNx/typora-theme-lapis/assets/86649490/adc0c85e-b7fd-405f-919d-99866f174b47">

现在mac下侧边栏样式应该能正常显示，可以 pull 最新代码试试还有无问题 🙌 

@leizhiyuan @hefengzz @qiudxx

**Comment by qiudxx** [comment]
<img width="441" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/24288438/4ef1d9c3-0794-4abb-8ba7-aa392263dc00">
有点问题

**Comment by YiNNx** [comment]
> <img alt="image" width="441" src="https://user-images.githubusercontent.com/24288438/239106808-4ef1d9c3-0794-4abb-8ba7-aa392263dc00.png"> @YiNNx 有点问题

标题内容会显示不全吗，能否给一个显示有问题的目录结构呢，感谢

**Comment by qiudxx** [comment]
<img width="633" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/24288438/36ad6bb7-1dcd-4687-9754-42b8cd839978">
正常目录是这样的

**Comment by Gypsophila64** [comment]
我的mac上也遇到了同样的问题
<img width="1363" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/81243109/76480a58-2e69-4159-9f97-3e25f8601307">

**Comment by YiNNx** [comment]
好神秘的 bug...

**Comment by YiNNx** [comment]
@qiudxx @Gypsophila64 
标题显示不全可能是字体文件的适配问题，见 https://github.com/YiNNx/typora-theme-lapis/issues/19#issuecomment-1556206990
试试将`lapis.css`中下面几行代码注释掉或者删除
```css
@font-face {
  font-family: "Cantarell";
  src: url('lapis/Cantarell-VF.otf');
}
```
看看是否能显示全
