### ISSUE TITLE
公式、html项目等元素的排版问题

### ISSUE THREAD

**Issue by Anyayay** [YiNNx/typora-theme-lapis#31]
右上角的标识与下面的项目应该进行向右对齐

![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/95ea5aef-0820-48a0-b39f-1c5d769de0eb)

> 这个还同时存在标识与下面的项目距离过近的问题

![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/5e6c4c78-4cfc-4d0a-8d5d-b53e1fc19ad7)

**Comment by YiNNx** [comment]
> 右上角的标识与下面的项目应该进行向右对齐

看了下，不对齐问题应该可以这样解决

```css
.md-rawblock-control:not(.md-rawblock-tooltip) {
    padding: 0;
}
```

> 这个还同时存在标识与下面的项目距离过近的问题

这里我也想调整下，但没找到合适的方法，欢迎提PR~
