### ISSUE TITLE
一个新的关于h2问题的解决方案

### ISSUE THREAD

**Issue by Anyayay** [YiNNx/typora-theme-lapis#45]
我又有一个关于h2问题的解决方案，摒弃现有的所有h2的代码，只用以下代码
```css
#write h2 {
    background-color: var(--header-span-color);
    color: #ffffff;
    padding: 1px 10px;
    border-radius: 4px;
    display: inline;  /* 添加这一行 */
}
```

这算是从根本上解决问题
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/b74bf8f2-8a57-48bb-ac52-7bfb55fab925)
> 这就只需要改一下样式颜色就够了

但是也存在一定问题：
```
## 标题1

## 标题2
```
上面会显示为：
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/24786933-e88a-405d-befc-1882939b1e54)
> 不过，应该不会出现多个标题放在一起吧，这个问题或可以忽略
